---
services:
  postgre-db:
    image: "postgres:15"
    container_name: postgre-db
    hostname: postgres
    environment:
      - POSTGRES_DB=basic_auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresP@ss
    ports:
      - "5433:5432"
    mem_reservation: "512M"
    mem_limit: "1024M"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d moviesdb -U Password123" ]
      timeout: 10s
      interval: 15s
      retries: 10
      start_period: 20s

  basic-auth:
    container_name: basic-auth
    build:
      context: ./basic-auth
      dockerfile: Dockerfile
    hostname: basic.auth.app
    depends_on:
      postgre-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - "BASIC_DEBUG=true"
    mem_reservation: "64M"
    mem_limit: "128M"
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.0.68:3100/loki/api/v1/push"
        loki-external-labels: container_name={{.ID}}.{{.Name}},cluster=compose
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 100ms
